### ISSUE TITLE
Is it still working? and how can i run it?

### ISSUE THREAD

**Issue by misterpeople** [Ed1123/visa_web_scraper#1]
/.

**Comment by misterpeople** [comment]
Im getting erros and could not figure out how to run it, Id like to talk with you privately if possible, thank you!@

**Comment by Ed1123** [comment]
Oh sure! I've never expected someone to actually need something like this so I abandoned it. The code in the repo needs some corrections that I only did locally when I was creating it. I'll try to take a look at them and update the repo.
We can chat about it for sure. :) If you know a safe way we can interchange contact information let me know.

**Comment by misterpeople** [comment]
Can you message me on telegram?
My username is @mrknowall1

**Comment by misterpeople** [comment]
🙏🙏

**Comment by Ed1123** [comment]
Answering your question regarding the robot helping find my appointment, it certainly did. First it gave a couple of alerts in the middle of the night that by the time I was awake and try to check, they were already gone. That was until I get an alert when I was having dinner. Then I get my appointment. ^^

**Comment by misterpeople** [comment]
Awesome, I'm waiting for the repo.
Any estimate time?

**Comment by Ed1123** [comment]
And about the reschedule part of the robot. It may not be reliable and I have no current plans of implement it. I'll try to make the basic robot to work this week.

**Comment by Ed1123** [comment]
It should be fixed now. Unfortunately, I cannot fully test it since my account doesn't have the same options as when I didn't have an appointment.
