### ISSUE TITLE
Do we know if it's legal to scrape this website?

### ISSUE THREAD

**Issue by HiphopopotamusRhymenoceros** [Ed1123/visa_web_scraper#10]
Hi,

I know this isn't a formal issue but I was curious if anyone knew if web scraping this website (`ais.usvisa-info.com`) is legal. I want to use this application but am concerned that my account could be flagged. 

Any thoughts? 

Thanks!

**Comment by Ed1123** [comment]
I think it is entirely legal as long as you use it responsibly. I set it up
so it checks every 10 minutes (which you could do manually). I won't worry
much about it.
