### ISSUE TITLE
Contact with you

### ISSUE THREAD

**Issue by misterpeople** [Ed1123/visa_web_scraper#9]
Hey, where can i contact you?

**Comment by Ed1123** [comment]
Hi! If it something related to the code in this project I think this is
best place to do so. If it something professional here is my LinkedIn
account: https://www.linkedin.com/in/edmv 🙂

**Comment by misterpeople** [comment]
ok

**Comment by Ed1123** [comment]
Yes, I do, but I don't use it that offen. I'd rather use my LinkedIn 🙂.
